# Generated by Django 5.1.2 on 2024-10-13 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
