# Generated by Django 5.1.2 on 2024-10-13 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_modified_date_post_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
